### ISSUE TITLE
com.intellij.diagnostic.PluginException on Markdown Editor 2.0.5

### ISSUE THREAD

**Issue by ofry** [shuzijun/markdown-editor#117]
```
IntelliJ IDEA 2024.1 (Ultimate Edition)
Build #IU-241.14494.240, built on March 28, 2024

Runtime version: 17.0.10+8-b1207.12 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.5.0-27-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 10240M
Cores: 4
Registry:
  ide.images.show.chessboard=true
Non-Bundled Plugins:
  com.jetbrains.plugins.ini4idea (241.14494.240)
  Batch Scripts Support (1.0.13)
  icu.windea.bbcode (1.8)
  com.mnr.java.intellij.idea.plugin.base64helper (3.0.0)
  dev.meanmail.plugin.nginx-intellij-plugin-pro (2022.1.1)
  intellij-awk (0.4.3.1)
  com.plugin.image-icon-viewer (1.0.11)
  com.shuzijun.markdown-editor (2.0.5)
  com.alayouni.ansiHighlight (24.1.0)
  org.intellij.RegexpTester (2.2.0)
  ru.limydesign.plugins.yandex.translate (0.1.0)
  artsiomch.cmake (241.0.1-EAP)
  artsiomch.cmake.plus (241.0.1-EAP)
  com.mnw.tabmover (1.5.2)
  ru.ilimurzin.bitrixexcluder (2.0.0)
  com.github.izhangzhihao.intellijgooglesearch (0.0.2)
  com.github.exidcuter.dockerregistryexplorer (1.1.0-stable)
  com.jetbrains.CyanTheme (1.3)
  com.intellij.apacheConfig (241.14494.240)
  com.vexus2.intellij.openingithub (1.0.6)
  org.jetbrains.plugins.stylus (241.14494.140)
  com.mroche.JsonHelper (1.3.2)
  de.ehmkah.projects.imgdiff (1.11.0)
  org.jetbrains.plugins.localization (241.14494.150)
  com.devwook.copy_path_helper (1.1.2)
  lermitage.intellij.extra.icons (2024.3.4)
  krasa.IdeaIconPack (1.14)
  Pythonid (241.14494.314)
  com.ess.terminal-pro (1.1.9.241)
  man-page-viewer (0.1.1)
  MHCommitMessageTemplate (1.0.3)
  String Manipulation (9.12.0)
  com.jetbrains.space (241.14494.150)
  GrepConsole (12.25.0-IJ2023.3)
  com.intellij.ml.llm (241.14494.240)
  com.majera.intellij.codereview.bitbucket (2024.1.6.241)
  git-extended-update-index (0.1.3)
  mobi.hsz.idea.gitignore (4.5.3)
  com.jetbrains.packagesearch.intellij-plugin (241.0.8)
  com.intellij.tide (241.14494.288)
  io.github.guoci.PythonDocumentationLinkProvider (0.1.4)
  org.tonybaloney.security.pycharm-security (1.29.0)
  ru.meanmail.plugins.prettify-python (2022.1)
  ru.meanmail.plugin.django_command_runner (2022.1)
  com.github.kawamataryo.copygithublink (0.5.3)
  com.majera.intellij.codereview.gitlab (2024.1.6.241)
  com.jetbrains.php (241.14494.240)
  com.niclas-van-eyk.laravel-make-integration (2.3.5)
  com.jetbrains.twig (241.14494.240)
  com.xu (1.3)
  com.funivan.idea.phpClean (2023.12.17)
  com.clutcher.comments_highlighter (2024.1.14)
  nl.deschepers.laraveltinker (2.7.0)
  ru.itrack.bitrix (0.2.0)
  com.kalessil.phpStorm.phpInspectionsUltimate-mp (2024.1.1)
  com.jetbrains.php.blade (241.14494.240)
  dev.ekvedaras.laravelquery (4.0.2)
  com.kalessil.phpStorm.yii2inspections (1.0.6)
  org.jetbrains.plugins.phpstorm-remote-interpreter (241.14494.158)
  org.jetbrains.plugins.phpstorm-docker (241.14494.158)
  com.jetbrains.php.framework (241.14494.240)
  com.jetbrains.php.wordPress (241.14494.240)
  ru.vkurdin.idea.php.lambdafolding (0.3.0)
  org.exbin.deltahex.intellij (0.2.10)
  com.wbars.php.folding (1.0.3)
  com.intellij.php.codeigniter3 (0.6.0)
  com.github.woru.options-completion-phpstorm-plugin (0.0.7)
  ru.adelf.idea.dotenv (2024.1)
  com.laravel_idea.plugin (8.1.4.241)
  com.eny.i18n (2.6.2)
  net.king2500.plugins.PhpAdvancedAutoComplete (1.1.0)
  de.espend.idea.php.toolbox (6.2.0)
  de.espend.idea.php.annotation (10.0.0)
  fr.adrienbrault.idea.symfony2plugin (2023.1.268)
  de.espend.idea.shopware (4.4.3)
  org.endpointdeps.EndpointDependencies (1.3)
  zielu.gittoolbox (500.2.3+233)
  com.firsttimeinforever.intellij.pdf.viewer.intellij-pdf-viewer (0.15.0)
Kotlin: 241.14494.240-IJ
Current Desktop: KDE
```

```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.shuzijun.markdown.editor.DevtoolsAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.shuzijun.markdown-editor]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)

```

**Comment by CoCoTeaNet** [comment]
+1我也收到这个报错

**Comment by maxl2287** [comment]
+1 
Please try to fix that.
