### ISSUE TITLE
idea 2022.1 点击 Markdown Editor 时，Idea 直接闪退

### ISSUE THREAD

**Issue by Codelifeguardian** [shuzijun/markdown-editor#47]
如题

**Comment by shuzijun** [comment]
检查idea日志里是否有相关日志可以提供一下

**Comment by shuzijun** [comment]
新版本已发布，试一下如果还有这种情况，再打开这个issue

**Comment by Codelifeguardian** [comment]
> 新版本已发布，试一下如果还有这种情况，再打开这个issue

### 还是会闪退，Idea 版本 2022.1.1

### 以下是可能相关的 Idea 日志
2022-05-15 19:10:22,966 [   3725]   INFO - STDERR - java.lang.ClassCastException: class com.intellij.openapi.fileEditor.TextEditorWithPreview$MyEditorLayeredComponentWrapper cannot be cast to class javax.swing.JPanel (com.intellij.openapi.fileEditor.TextEditorWithPreview$MyEditorLayeredComponentWrapper is in unnamed module of loader com.intellij.util.lang.PathClassLoader @71e7a66b; javax.swing.JPanel is in module java.desktop of loader 'bootstrap')
2022-05-15 19:10:22,966 [   3725]   INFO - STDERR - 	at net.vektah.codeglance2.EditorPanelInjector.getPanel(EditorPanelInjector.kt:56)
2022-05-15 19:10:22,966 [   3725]   INFO - STDERR - 	at net.vektah.codeglance2.EditorPanelInjector.inject(EditorPanelInjector.kt:82)
2022-05-15 19:10:22,966 [   3725]   INFO - STDERR - 	at net.vektah.codeglance2.EditorPanelInjector.fileOpened(EditorPanelInjector.kt:31)
2022-05-15 19:10:22,966 [   3725]   INFO - STDERR - 	at com.intellij.util.messages.impl.MessageBusImpl.invokeMethod(MessageBusImpl.java:642)
2022-05-15 19:10:22,966 [   3725]   INFO - STDERR - 	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:621)
2022-05-15 19:10:22,966 [   3725]   INFO - STDERR - 	at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:417)
2022-05-15 19:10:22,966 [   3725]   INFO - STDERR - 	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:391)
2022-05-15 19:10:22,966 [   3725]   INFO - STDERR - 	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:373)
2022-05-15 19:10:22,966 [   3725]   INFO - STDERR - 	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:34)
2022-05-15 19:10:22,966 [   3725]   INFO - STDERR - 	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:180)
2022-05-15 19:10:22,966 [   3725]   INFO - STDERR - 	at com.sun.proxy.$Proxy114.fileOpened(Unknown Source)
2022-05-15 19:10:22,966 [   3725]   INFO - STDERR - 	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl4Edt$20(FileEditorManagerImpl.java:1071)
2022-05-15 19:10:22,966 [   3725]   INFO - STDERR - 	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$7.lambda$run$0(FileEditorManagerImpl.java:1156)
2022-05-15 19:10:22,966 [   3725]   INFO - STDERR - 	at com.intellij.openapi.util.ExpirableRunnable$1.run(ExpirableRunnable.java:17)
2022-05-15 19:10:22,966 [   3725]   INFO - STDERR - 	at com.intellij.openapi.wm.impl.FocusManagerImpl.lambda$doWhenFocusSettlesDown$3(FocusManagerImpl.java:181)
2022-05-15 19:10:22,966 [   3725]   INFO - STDERR - 	at com.intellij.util.ui.EdtInvocationManager.invokeLaterIfNeeded(EdtInvocationManager.java:101)
2022-05-15 19:10:22,966 [   3725]   INFO - STDERR - 	at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.java:179)
2022-05-15 19:10:22,966 [   3725]   INFO - STDERR - 	at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.java:132)
2022-05-15 19:10:22,966 [   3725]   INFO - STDERR - 	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:172)
2022-05-15 19:10:22,966 [   3725]   INFO - STDERR - 	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:178)
2022-05-15 19:10:22,966 [   3725]   INFO - STDERR - 	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$7.run(FileEditorManagerImpl.java:1155)
2022-05-15 19:10:22,966 [   3725]   INFO - STDERR - 	at com.intellij.openapi.util.BusyObject$Impl$Simple.execute(BusyObject.java:105)
2022-05-15 19:10:22,966 [   3725]   INFO - STDERR - 	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.notifyPublisher(FileEditorManagerImpl.java:1152)
2022-05-15 19:10:22,966 [   3725]   INFO - STDERR - 	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4Edt(FileEditorManagerImpl.java:1068)
2022-05-15 19:10:22,966 [   3725]   INFO - STDERR - 	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl4$17(FileEditorManagerImpl.java:961)
2022-05-15 19:10:22,966 [   3725]   INFO - STDERR - 	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.runBulkTabChange(FileEditorManagerImpl.java:1697)
2022-05-15 19:10:22,966 [   3725]   INFO - STDERR - 	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl4$18(FileEditorManagerImpl.java:960)
2022-05-15 19:10:22,966 [   3725]   INFO - STDERR - 	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:215)
2022-05-15 19:10:22,967 [   3726]   INFO - STDERR - 	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
2022-05-15 19:10:22,967 [   3726]   INFO - STDERR - 	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:197)
2022-05-15 19:10:22,967 [   3726]   INFO - STDERR - 	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
2022-05-15 19:10:22,967 [   3726]   INFO - STDERR - 	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
2022-05-15 19:10:22,967 [   3726]   INFO - STDERR - 	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:96)
2022-05-15 19:10:22,967 [   3726]   INFO - STDERR - 	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
2022-05-15 19:10:22,967 [   3726]   INFO - STDERR - 	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
2022-05-15 19:10:22,967 [   3726]   INFO - STDERR - 	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
2022-05-15 19:10:22,967 [   3726]   INFO - STDERR - 	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
2022-05-15 19:10:22,967 [   3726]   INFO - STDERR - 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
2022-05-15 19:10:22,967 [   3726]   INFO - STDERR - 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
2022-05-15 19:10:22,967 [   3726]   INFO - STDERR - 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
2022-05-15 19:10:22,967 [   3726]   INFO - STDERR - 	at java.base/java.security.AccessController.doPrivileged(Native Method)
2022-05-15 19:10:22,967 [   3726]   INFO - STDERR - 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
2022-05-15 19:10:22,967 [   3726]   INFO - STDERR - 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
2022-05-15 19:10:22,967 [   3726]   INFO - STDERR - 	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
2022-05-15 19:10:22,967 [   3726]   INFO - STDERR - 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
2022-05-15 19:10:22,967 [   3726]   INFO - STDERR - 	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
2022-05-15 19:10:22,967 [   3726]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
2022-05-15 19:10:22,967 [   3726]   INFO - STDERR - 	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
2022-05-15 19:10:22,967 [   3726]   INFO - STDERR - 	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
2022-05-15 19:10:22,967 [   3726]   INFO - STDERR - 	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
2022-05-15 19:10:22,967 [   3726]   INFO - STDERR - 	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
2022-05-15 19:10:22,967 [   3726]   INFO - STDERR - 	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
2022-05-15 19:10:22,967 [   3726]   INFO - STDERR - 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
2022-05-15 19:10:22,967 [   3726]   INFO - STDERR - 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
2022-05-15 19:10:22,967 [   3726]   INFO - STDERR - 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
2022-05-15 19:10:22,967 [   3726]   INFO - STDERR - 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
2022-05-15 19:10:22,967 [   3726]   INFO - STDERR - 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
2022-05-15 19:10:22,967 [   3726]   INFO - STDERR - 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
2022-05-15 19:10:22,967 [   3726]   INFO - STDERR - 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
2022-05-15 19:10:22,977 [   3736]   INFO - #c.s.m.e.MarkdownPreviewFileEditor - markdown style: <style id="ideaStyle">.vditor{--panel-background-color:rgba(255,255,255,1.00);--textarea-background-color:rgba(255,255,255,1.00);--toolbar-background-color:rgba(255,255,255,1.00);}::-webkit-scrollbar-track {background-color:rgba(255,255,255,1.00);}::-webkit-scrollbar-thumb {background-color:rgba(115,115,115,0.20);}.vditor-reset {font-size:18px;font-family:"Courier New","Helvetica Neue","Luxi Sans","DejaVu Sans","Hiragino Sans GB","Microsoft Yahei",sans-serif,"Apple Color Emoji","Segoe UI Emoji","Noto Color Emoji","Segoe UI Symbol","Android Emoji","EmojiSymbols";color:rgba(8,8,8,1.00);}.vditor-reset table {color:rgba(8,8,8,1.00);}</style> ; Darcula: false
2022-05-15 19:10:22,982 [   3741]   WARN - #n.v.c.EditorPanelInjector - Injection failed
2022-05-15 19:10:22,982 [   3741]   INFO - STDERR - java.lang.ClassCastException: class com.intellij.openapi.fileEditor.TextEditorWithPreview$MyEditorLayeredComponentWrapper cannot be cast to class javax.swing.JPanel (com.intellij.openapi.fileEditor.TextEditorWithPreview$MyEditorLayeredComponentWrapper is in unnamed module of loader com.intellij.util.lang.PathClassLoader @71e7a66b; javax.swing.JPanel is in module java.desktop of loader 'bootstrap')

**Comment by shuzijun** [comment]
net.vektah.codeglance2
